### ISSUE TITLE
Unable to java -jar RSClient.java

### ISSUE THREAD

**Issue by nwmeyers** [bmoyer/osrsclient#10]
Hello bmoyer!

I am really interested in your client, however, I am unable to properly use it. I added the RSClient.jar to my path like mentioned (export PATH=$PATH:/home/test/Desktop/osrsclient/dist/RSClient.jar
 this may be the problem... I feel like I need to add more but with looking at your files I could not be sure what). Though, I feel like I am missing something or something else needs to be added to the path. The error that I get is the following: 

sudo java -jar osrsclient/dist/RSClient.jar Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/pircbotx/exception/IrcException
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.pircbotx.exception.IrcException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more

If you have any recommendations please let me know. 

Thank you,
nwmeyers

**Comment by richardgorman** [comment]
I have the same error.

**Comment by nwmeyers** [comment]
You have to use netbeans. Open the project in netbeans, and everything will work fine.

Let me know if you have anymore problems.

**Comment by richardgorman** [comment]
I am curious if it would be possible to switch the whole GUI over to JavaFX. Can you load the applet into a JavaFX node somehow?

**Comment by bmoyer** [comment]
Sorry for my lack of a response on this issue. @nwmeyers' advice of opening/compiling using Netbeans should do the trick.

I haven't looked into JavaFX very much, but it is most likely possible to load the OSRS applet into a JavaFX interface. I'd actually like to rework the entire GUI using something like JavaFX, as Swing is pretty dated (hell, it was dated when I started the project..).

**Comment by richardgorman** [comment]
I've tried but unsuccessfully (I'm not well versed with Java). Perhaps we should work together? I want to make a osrs client just as a programming exercise

**Comment by trevorsenior** [comment]
@richardgorman You can get this to build without netbeans with a modified setup. See:

https://github.com/trevorsenior/osrsclient/commit/ad9eceb3f766dd0d12b041853267e9c48b0d75db

I'm hacking away on this to learn a bit more about, well, how this kind of stuff works. I don't actually plan on doing anything serious with it.
